apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: cosign-verified-manifests
spec:
  version: v1.0
  fetch:
    command: [/usr/local/bin/verify-cmp, fetch]
  generate:
    command: [/usr/local/bin/verify-cmp, generate]
